[gobal]
upgrade_only = true
system = "linux/amd64"

["brave/brave-browser"] # https://github.com/brave/brave-browser
target = "~/.local/bin"
system = "linux/amd64"
asset_filters = ["^asc", "amd64"]

["BurntSushi/ripgrep"] # https://github.com/BurntSushi/ripgrep
target = "~/.local/bin/rg"
asset_filters = ["gnu"]

["sharkdp/fd"] # https://github.com/sharkdp/fd
target = "~/.local/bin"
asset_filters = ["gnu"]

["sharkdp/bat"] # https://github.com/sharkdp/bat
target = "~/.local/bin"
asset_filters = ["gnu"]

["cli/cli"] # https://github.com/cli/cli
target = "~/.local/bin"
asset_filters = ["tar.gz"]

["zyedidia/eget"] # https://github.com/zyedidia/eget
target = "~/.local/bin"

["jdxcode/rtx"]
target = "~/.local/bin"
asset_filters = ["tar.gz"]

["dbrgn/tealdeer"]
target = "~/.local/bin/tldr"

["yt-dlp/yt-dlp"] # https://github.com/yt-dlp/yt-dlp
target = "~/.local/bin/"
asset_filters = ["^arm", "^arch", "^zip"]
